### ISSUE TITLE
Can you please update plugin to 1.20.2 ? 

### ISSUE THREAD

**Issue by Gottor** [mrmrmystery/Mixer#1]
[Server thread/INFO]: [mixer] Loading server plugin Mixer v1.0.0
[23:30:24] [Server thread/ERROR]: [mixer] Error initializing plugin 'Mixer-1.0-SNAPSHOT-dev-all.jar' in folder 'plugins' (Is it up to date?)
net.somewhatcity.mixer.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.20.2
	at net.somewhatcity.mixer.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:72) ~[Mixer-1.0-SNAPSHOT-dev-all.jar:?]
	at net.somewhatcity.mixer.commandapi.CommandAPI.onLoad(CommandAPI.java:103) ~[Mixer-1.0-SNAPSHOT-dev-all.jar:?]
	at net.somewhatcity.mixer.Mixer.onLoad(Mixer.java:28) ~[Mixer-1.0-SNAPSHOT-dev-all.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:526) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2082]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mrmrmystery** [comment]
Done! https://modrinth.com/plugin/mixer/version/1.0.1
